image: golang:latest

stages:
  - lint
  - test

go_vet:
  stage: lint
  script:
    - go vet $(go list ./... | grep -v /vendor/)

go_fmt:
  stage: lint
  script:
    - go fmt $(go list ./... | grep -v /vendor/)

golangci:
  stage: lint
  image:
    name: docker.io/golangci/golangci-lint:v1.50.1
    entrypoint: ['']
  script:
    - golangci-lint run -v

go_test:
  stage: test
  coverage: '/coverage: (\d+\.\d+)/'
  script:
    - go test -v -cover ./...
